services:
  - type: web
    name: jefram-stores
    runtime: static
    buildCommand: ""
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /admin/*
        destination: /admin/index.html